### ISSUE TITLE
How I can make page button navigation with the url instead of setState and change history?

### ISSUE THREAD

**Issue by duongductrong** [thijssmudde/react-headless-pagination#10]

**Comment by horaciosystem** [comment]
Have you saw this on the readme? Perhaps could help.

```
[as](https://github.com/thijssmudde/react-headless-pagination#as)
Type: React.ReactElement Default:

Provide a custom React Element, such as a next/link component.
```

Also, with the callback **setCurrentPage** you can do as you need – persisting the page at the URL, and use the **currentPage** prop that can be reading from the URL param.
