### ISSUE TITLE
classnames replace with clsx

### ISSUE THREAD

**Issue by dcheglakov** [thijssmudde/react-headless-pagination#12]
Hey,

Is it possible to replace classname with clsx as a compact alternative?

Here is a comparison:
- [classnames](https://bundlephobia.com/package/classnames@2.3.2)
- [clsx](https://bundlephobia.com/package/clsx@2.0.0)

**Comment by thijssmudde** [comment]
Sure @dcheglakov.

**Comment by thijssmudde** [comment]
Completed in PR https://github.com/thijssmudde/react-headless-pagination/pull/13
