### ISSUE TITLE
Module not found: Can't resolve 'classnames'

### ISSUE THREAD

**Issue by Ding-Fan** [thijssmudde/react-headless-pagination#3]
`./node_modules/react-headless-pagination/dist/react-headless-pagination.esm.js:2:0
Module not found: Can't resolve 'classnames'`

maybe it should be add into dependencies

**Comment by thijssmudde** [comment]
Will be fixed in 0.2.1: https://github.com/fullhdpixel/react-headless-pagination/releases/tag/0.2.1
