### ISSUE TITLE
Support Next.js

### ISSUE THREAD

**Issue by lightsound** [thijssmudde/react-headless-pagination#4]
Thank you for your great library. This is a feature request.

The following error occurs when used with Next.js.

```
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

I can use `useEffect` or `dynamic import` to get around this, but I would prefer to use this library in a SSR environment if possible. I look forward to Next.js support.

**Comment by thijssmudde** [comment]
Just tested the library with a new nextjs typescript app and no issues:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/7371397/193409226-6e2cffb0-708e-4449-81d3-c04a8f36443e.png">

```
 "dependencies": {
    "classnames": "^2.3.2",
    "next": "12.3.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-headless-pagination": "^0.2.1"
  },
  "devDependencies": {
    "@types/node": "18.7.23",
    "@types/react": "18.0.21",
    "@types/react-dom": "18.0.6",
    "eslint": "8.24.0",
    "eslint-config-next": "12.3.1",
    "typescript": "4.8.4"
  }
```

Please provide an example repo to demonstrate the issue.
