### ISSUE TITLE
Feature request: Usage with Router

### ISSUE THREAD

**Issue by junwen-k** [thijssmudde/react-headless-pagination#5]
Greetings, thanks for writing up this great library.

There is currently an issue where wrappers are hard-coded. To be truly headless, users should be able to change the wrapper tag to something else. E.g, `<Link>` component for each page button instead of `<span>`.

Potential solution is to add custom renderer function for more flexibility.

Thanks.

**Comment by 58bits** [comment]
Agreed - this would be a nice touch - similar to the way in which Radix UI offers an `asChild` prop - which we use extensively.

**Comment by 58bits** [comment]
For example...

https://github.com/infonomic/react-headless-pagination/blob/feat/radix-primitive-version/src/Pagination/Pagination.tsx

We use Radix UI, and so aren't afraid of the Radix primitive dependency, but you might want to do something a little different.

I've only lightly tested this with your current Storybook setup, and it's not complete yet - but we may create a fuller implementation along these lines.

Hope this helps.

**Comment by janekolszak** [comment]
This would be perfect
